//! `-errorinfo`, `-errorcode`, `-errorline`, `$::errorInfo` and `$::errorCode` against answers recorded from the reference interpreter.

mod golden;

use golden::ok;

#[test]
fn pinned() {
    golden::check(
        "r2_errorinfo_golden",
        &[
            ok("errorinfo_error_command_in_proc_levels", "proc show {script} {\n  catch {uplevel #0 $script} m o\n  puts $m\n  puts [dict get $o -errorinfo]\n  puts [dict get $o -errorcode]\n  puts [dict get $o -errorline]\n}\nshow {error foo}\nshow {proc p {} {error inner}; p}\nshow {proc q {a} {p}; q 1}\nshow {eval {eval {error deep}}}\nshow {uplevel 0 {error up}}\n", "foo\nfoo\n    while executing\n\"error foo\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nNONE\n2\ninner\ninner\n    while executing\n\"error inner\"\n    (procedure \"p\" line 1)\n    invoked from within\n\"p\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nNONE\n2\ninner\ninner\n    while executing\n\"error inner\"\n    (procedure \"p\" line 1)\n    invoked from within\n\"p\"\n    (procedure \"q\" line 1)\n    invoked from within\n\"q 1\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nNONE\n2\ndeep\ndeep\n    while executing\n\"error deep\"\n    (\"eval\" body line 1)\n    invoked from within\n\"eval {error deep}\"\n    (\"eval\" body line 1)\n    invoked from within\n\"eval {eval {error deep}}\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nNONE\n2\nup\nup\n    while executing\n\"error up\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel 0 {error up}\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nNONE\n2\n"),
            ok("errorinfo_inline_bodies_and_foreach_context", "proc show {script} {\n  catch {uplevel #0 $script} m o\n  puts [dict get $o -errorinfo]\n}\nshow {if {1} {error inif}}\nshow {while {1} {error inwhile}}\nshow {foreach i {1 2} {error inforeach}}\nshow {lmap i {1 2} {error inlmap}}\nshow {dict for {k v} {a 1} {error indictfor}}\nshow {foreach i {1} {foreach j {2} {error nestedfe}}}\nshow {namespace eval nsx {error innsx}}\nshow {proc w {} {foreach i {1} {error inw}}; w}\nshow {proc w {} {set d {a 1}; dict with d {error indw}}; w}\n", "inif\n    while executing\n\"error inif\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\ninwhile\n    while executing\n\"error inwhile\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\ninforeach\n    while executing\n\"error inforeach\"\n    (\"foreach\" body line 1)\n    invoked from within\n\"foreach i {1 2} {error inforeach}\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\ninlmap\n    while executing\n\"error inlmap\"\n    (\"lmap\" body line 1)\n    invoked from within\n\"lmap i {1 2} {error inlmap}\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nindictfor\n    while executing\n\"error indictfor\"\n    (\"dict for\" body line 1)\n    invoked from within\n\"dict for {k v} {a 1} {error indictfor}\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nnestedfe\n    while executing\n\"error nestedfe\"\n    (\"foreach\" body line 1)\n    invoked from within\n\"foreach j {2} {error nestedfe}\"\n    (\"foreach\" body line 1)\n    invoked from within\n\"foreach i {1} {foreach j {2} {error nestedfe}}\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\ninnsx\n    while executing\n\"error innsx\"\n    (in namespace eval \"::nsx\" script line 1)\n    invoked from within\n\"namespace eval nsx {error innsx}\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\ninw\n    while executing\n\"error inw\"\n    (procedure \"w\" line 1)\n    invoked from within\n\"w\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nindw\n    while executing\n\"error indw\"\n    (procedure \"w\" line 1)\n    invoked from within\n\"w\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\n"),
            ok("errorinfo_preset_and_return_origin", "proc show {script} {\n  catch {uplevel #0 $script} m o\n  puts [dict get $o -errorinfo]\n  puts [dict get $o -errorcode]\n}\nshow {error msg {custom info} {MY CODE}}\nshow {proc t {} {return -code error terr}; t}\nshow {proc rt {} {return -code error -errorinfo ei0 -errorcode {C D} rtmsg}; rt}\nshow {proc rr {} {catch {error first} m o; return -options $o $m}; rr}\nshow {proc u {} {error x}; proc v {} {u}; if {[catch v m]} {error \"wrapped: $m\"}}\n", "custom info\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nMY CODE\nterr\n    while executing\n\"t\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nNONE\nei0\n    invoked from within\n\"rt\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nC D\nfirst\n    while executing\n\"error first\"\n    (procedure \"rr\" line 1)\n    invoked from within\n\"rr\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nNONE\nwrapped: x\n    while executing\n\"error \"wrapped: $m\"\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nNONE\n"),
            ok("errorinfo_multiline_and_line_numbers", "proc show {script} {\n  catch {uplevel #0 $script} m o\n  puts [dict get $o -errorinfo]\n}\nshow {proc w2 {} {\n  set a 1\n  set b 2\n  error multiline\n}\nw2}\nshow {\nerror {line two of script}\n}\nshow {error \"multi\nline msg\"}\nshow {proc p {a b} {error \"in p $a\"}; p 1 [string repeat x 40]}\nshow {namespace eval n {proc q {} {error nq}}; n::q}\n", "multiline\n    while executing\n\"error multiline\"\n    (procedure \"w2\" line 4)\n    invoked from within\n\"w2\"\n    (\"uplevel\" body line 6)\n    invoked from within\n\"uplevel #0 $script\"\nline two of script\n    while executing\n\"error {line two of script}\"\n    (\"uplevel\" body line 2)\n    invoked from within\n\"uplevel #0 $script\"\nmulti\nline msg\n    while executing\n\"error \"multi\nline msg\"\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nin p 1\n    while executing\n\"error \"in p $a\"\"\n    (procedure \"p\" line 1)\n    invoked from within\n\"p 1 [string repeat x 40]\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nnq\n    while executing\n\"error nq\"\n    (procedure \"n::q\" line 1)\n    invoked from within\n\"n::q\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\n"),
            ok("errorcode_defaults_and_classification", "foreach script {\n  {error plain}\n  {nosuchcmd 1 2}\n  {expr {1/0}}\n  {expr {abc + 1}}\n  {expr {1 +}}\n  {expr {(1}}\n  {expr {$}}\n  {lindex}\n  {string foo bar}\n  {dict get {a 1} b}\n  {incr nonexistent_zz zz}\n  {set x abc; incr x}\n  {set x 1.5; incr x}\n  {puts $undefined_var}\n  {unset undefined_var}\n  {set a(1) 2; set a(2)}\n  {regexp {(} abc}\n  {uplevel 9 {}}\n  {namespace delete nosuchns}\n  {lsearch -zz a b}\n  {expr {1 << -1}}\n  {throw {MY CODE} msg}\n} {\n  catch {eval $script} m o\n  puts \"[lindex $script 0] -> [dict get $o -errorcode]\"\n}\nproc local {} {\n  foreach script {\n    {puts $undefined_local}\n    {unset undefined_local}\n    {set a(1) 2; set a(2)}\n  } {\n    catch {eval $script} m o\n    puts \"proc [lindex $script 0] -> [dict get $o -errorcode]\"\n  }\n  puts [catch {puts $undefined_local2} m o]\n  puts [dict get $o -errorcode]\n  puts [catch {unset undefined_local3} m o]\n  puts [dict get $o -errorcode]\n}\nlocal\n", "error -> NONE\nnosuchcmd -> TCL LOOKUP COMMAND nosuchcmd\nexpr -> ARITH DIVZERO {divide by zero}\nexpr -> TCL PARSE EXPR BAREWORD\nexpr -> TCL PARSE EXPR MISSING\nexpr -> TCL PARSE EXPR UNBALANCED\nexpr -> TCL PARSE EXPR BADCHAR\nlindex -> TCL WRONGARGS\nstring -> TCL LOOKUP SUBCOMMAND foo\ndict -> TCL LOOKUP DICT b\nincr -> TCL VALUE NUMBER\nset -> TCL VALUE NUMBER\nset -> TCL VALUE INTEGER\nputs -> TCL LOOKUP VARNAME undefined_var\nunset -> TCL LOOKUP VARNAME undefined_var\nset -> TCL READ VARNAME\nregexp -> REGEXP REG_EPAREN {parentheses () not balanced}\nuplevel -> TCL LOOKUP LEVEL 9\nnamespace -> TCL LOOKUP NAMESPACE nosuchns\nlsearch -> TCL LOOKUP INDEX option -zz\nexpr -> NONE\nthrow -> MY CODE\nproc puts -> TCL LOOKUP VARNAME undefined_local\nproc unset -> TCL LOOKUP VARNAME undefined_local\nproc set -> TCL READ VARNAME\n1\nTCL READ VARNAME\n1\nTCL UNSET VARNAME\n"),
            ok("errorinfo_variables_after_catch", "catch {error one {info one} {CODE ONE}} m\nputs $::errorInfo\nputs $::errorCode\nproc p {} {error two}\ncatch p m\nputs $::errorInfo\nputs $::errorCode\ncatch {expr {1/0}} m\nputs $::errorCode\nputs [info exists ::errorInfo]\n", "info one\nCODE ONE\ntwo\n    while executing\n\"error two\"\n    (procedure \"p\" line 1)\n    invoked from within\n\"p\"\nNONE\nARITH DIVZERO {divide by zero}\n1\n"),
            ok("errorinfo_try_finally_and_handlers_reraise", "proc show {script} {\n  catch {uplevel #0 $script} m o\n  puts [dict get $o -errorinfo]\n}\nshow {try {error inbody} finally {set z 1}}\nshow {proc f {} {try {error a} on error {m} {error inh}}; f}\nshow {proc f {} {try {error ina} finally {set z 1}}; f}\n", "inbody\n    while executing\n\"error inbody\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\ninh\n    while executing\n\"error inh\"\n    (procedure \"f\" line 1)\n    invoked from within\n\"f\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\nina\n    while executing\n\"error ina\"\n    (procedure \"f\" line 1)\n    invoked from within\n\"f\"\n    (\"uplevel\" body line 1)\n    invoked from within\n\"uplevel #0 $script\"\n"),
        ],
    );
}
