//! `trace` against answers recorded from the reference interpreter.

mod golden;

use golden::ok;

#[test]
fn pinned() {
    golden::check(
        "r2_trace_golden",
        &[
            ok("trace_variable_fires_on_each_access", "proc cb {args} {puts \"cb: $args\"}\nset x 1\ntrace add variable x {read write unset} cb\nputs \"--- read\"; set y $x\nputs \"--- write\"; set x 2\nputs \"--- incr\"; incr x\nputs \"--- append\"; append x a\nputs \"--- lappend\"; lappend x b\nputs \"--- unset\"; unset x\nputs [trace info variable x]\nset x 5\nputs [trace info variable x]\n", "--- read\ncb: x {} read\n--- write\ncb: x {} write\n--- incr\ncb: x {} read\ncb: x {} write\n--- append\ncb: x {} write\n--- lappend\ncb: x {} read\ncb: x {} write\n--- unset\ncb: x {} unset\n\n\n"),
            ok("trace_info_remove_and_ordering", "proc cb {args} {puts \"cb: $args\"}\nset x 1\ntrace add variable x write cb\ntrace add variable x {read write} {cb extra}\ntrace add variable x unset cb\nputs [trace info variable x]\nset x 2\ntrace remove variable x write cb\nputs [trace info variable x]\ntrace remove variable x {read write} {cb extra}\ntrace remove variable x unset cb\nputs [trace info variable x]\nputs [catch {trace remove variable x write nosuch} m]\n", "{unset cb} {{read write} {cb extra}} {write cb}\ncb: extra x {} write\ncb: x {} write\n{unset cb} {{read write} {cb extra}}\n\n0\n"),
            ok("trace_elements_and_array_variables", "proc cb {args} {puts \"cb: $args\"}\ntrace add variable a write cb\nset a(1) x\nset a(2) y\nputs [catch {set a} m]; puts $m\ntrace add variable b {read unset} cb\narray set b {1 2 3 4}\nset v $b(1)\nunset b(1)\nputs [trace info variable b]\nunset b\nputs [trace info variable b]\n", "cb: a 1 write\ncb: a 2 write\n1\ncan't read \"a\": variable is array\ncb: b 1 read\ncb: b(1) 1 unset\n{{read unset} cb}\ncb: b {} unset\n\n"),
            ok("trace_callback_errors_and_modification", "set m 5\ntrace add variable m read {apply {{n1 n2 op} {global m; set m 99}}}\nputs [set m]\ntrace add variable e write {apply {{n1 n2 op} {error \"trace says no\"}}}\nputs [catch {set e 1} msg]; puts $msg\nputs [info exists e]\nproc cb {args} {puts \"cb: $args\"}\nset x 0\ntrace add variable x {read write} cb\nproc p {} {global x; set x 7; puts \"p: $x\"}\np\nputs \"val=$x\"\nputs [expr {$x + 1}]\n", "99\n1\ncan't set \"e\": trace says no\n1\ncb: x {} write\ncb: x {} read\np: 7\ncb: x {} read\nval=7\ncb: x {} read\n8\n"),
            ok("trace_command_rename_and_delete", "proc cb {args} {puts \"cb: $args\"}\nproc foo {} {return foo}\ntrace add command foo {rename delete} cb\nrename foo bar\nputs [trace info command bar]\nrename bar {}\nputs [catch {trace info command bar} m]; puts $m\n", "cb: ::foo ::bar rename\n{{rename delete} cb}\ncb: ::bar {} delete\n1\nunknown command \"bar\"\n"),
            ok("trace_execution_enter_and_leave", "proc cb {args} {puts \"cb: $args\"}\nproc ex {a} {return [expr {$a*2}]}\ntrace add execution ex {enter leave} cb\nputs [ex 4]\nputs [trace info execution ex]\ntrace remove execution ex {enter leave} cb\nputs [ex 5]\nproc bad {} {error boom}\ntrace add execution bad leave cb\nputs [catch bad m]; puts $m\n", "cb: {ex 4} enter\ncb: {ex 4} 0 8 leave\n8\n{{enter leave} cb}\n10\ncb: bad 1 boom leave\n1\nboom\n"),
            ok("trace_argument_errors", "foreach c {\n {trace add variable x {} cb}\n {trace add variable x {re} cb}\n {trace add variable x {read bogus} cb}\n {trace add command x {read} cb}\n {trace add command nosuch {rename} cb}\n {trace add execution x {read} cb}\n {trace add variable x read cb extra}\n {trace remove variable x}\n {trace info variable x extra}\n {trace info command nosuch}\n {trace info bogus x}\n {trace foo}\n {trace add}\n {trace add variable x}\n {trace add bogus x write cb}\n {trace}\n {trace info variable}\n {trace add variable ::nons::x write cb}\n} {\n  puts \"$c => [catch $c m] $m\"\n}\n", "trace add variable x {} cb => 1 bad operation list \"\": must be one or more of array, read, unset, or write\ntrace add variable x {re} cb => 1 bad operation \"re\": must be array, read, unset, or write\ntrace add variable x {read bogus} cb => 1 bad operation \"bogus\": must be array, read, unset, or write\ntrace add command x {read} cb => 1 bad operation \"read\": must be delete or rename\ntrace add command nosuch {rename} cb => 1 unknown command \"nosuch\"\ntrace add execution x {read} cb => 1 bad operation \"read\": must be enter, leave, enterstep, or leavestep\ntrace add variable x read cb extra => 1 wrong # args: should be \"trace add variable name opList command\"\ntrace remove variable x => 1 wrong # args: should be \"trace remove variable name opList command\"\ntrace info variable x extra => 1 wrong # args: should be \"trace info variable name\"\ntrace info command nosuch => 1 unknown command \"nosuch\"\ntrace info bogus x => 1 bad option \"bogus\": must be execution, command, or variable\ntrace foo => 1 bad option \"foo\": must be add, info, or remove\ntrace add => 1 wrong # args: should be \"trace add type ?arg ...?\"\ntrace add variable x => 1 wrong # args: should be \"trace add variable name opList command\"\ntrace add bogus x write cb => 1 bad option \"bogus\": must be execution, command, or variable\ntrace => 1 wrong # args: should be \"trace option ?arg ...?\"\ntrace info variable => 1 wrong # args: should be \"trace info variable name\"\ntrace add variable ::nons::x write cb => 1 can't trace \"::nons::x\": parent namespace doesn't exist\n"),
        ],
    );
}
