#!/usr/bin/env python3
"""Generate src/tk/generated.rs from the Tcl stub declaration headers.

The stub tables are pure ABI: slot *order* is the contract and a name is only a
label for it. Writing 1000+ function-pointer slots by hand would guarantee an
off-by-one somewhere, so this derives them from a Tcl source tree instead.

The headers cannot be scraped with a regex. `TclPlatStubs` and
`TclIntPlatStubs` are declared once with `#ifdef _WIN32 / MAC_OSX_TCL / UNIX`
arms *inside* the struct body (tclIntPlatDecls.h:249-347 in 9.0.4), so which
members exist, and therefore what each slot index means, depends on the build
platform. The only correct reader is the C preprocessor, so this runs `cc -E`
over the headers with the same defines the Tk build used and parses that.

Usage:

    python3 scripts/gen_tk_stubs.py conformance/vendor/tcl9.0.4

against the checksum-verified tree `conformance/fetch-suite.sh` unpacks. The
output is committed; this script exists so the committed file can be
re-derived and diffed rather than trusted. `tests/tk_abi.rs` re-derives the
same names at test time when a source tree is present and fails if the
committed table has drifted.
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

# (C struct name, Rust const prefix, Table enum variant)
TABLES = [
    ("TclStubs", "TCL", "Tcl"),
    ("TclIntStubs", "TCL_INT", "TclInt"),
    ("TclPlatStubs", "TCL_PLAT", "TclPlat"),
    ("TclIntPlatStubs", "TCL_INT_PLAT", "TclIntPlat"),
]

# What the macOS Tk build compiles with. MAC_OSX_TCL selects the Darwin arms of
# the platform stub tables; USE_TCL_STUBS is what makes the tables the calling
# convention in the first place.
DEFINES = ["-DMAC_OSX_TCL=1", "-DUSE_TCL_STUBS=1"]


def preprocess(root: Path) -> str:
    src = "\n".join(
        [
            "#include <tclInt.h>",
            "#include <tclIntDecls.h>",
            "#include <tclIntPlatDecls.h>",
            "",
        ]
    )
    with tempfile.NamedTemporaryFile("w", suffix=".c", delete=False) as f:
        f.write(src)
        path = f.name
    cmd = [
        "cc",
        "-E",
        f"-I{root / 'generic'}",
        f"-I{root / 'unix'}",
        f"-I{root / 'macosx'}",
        *DEFINES,
        path,
    ]
    out = subprocess.run(cmd, capture_output=True, text=True)
    if out.returncode != 0:
        sys.stderr.write(out.stderr)
        raise SystemExit(f"preprocessing failed: {' '.join(cmd)}")
    return out.stdout


def slot_names(text: str, struct: str) -> list[str]:
    pat = re.compile(
        r"typedef struct " + struct + r" \{(.*?)\}\s*" + struct + r"\s*;", re.S
    )
    found = pat.findall(text)
    if len(found) != 1:
        raise SystemExit(f"{struct}: expected 1 definition after cpp, got {len(found)}")
    return re.findall(r"\(\*(\w+)\)", found[0])


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: gen_tk_stubs.py <tcl-source-root>")
    root = Path(sys.argv[1])
    text = preprocess(root)

    out = [
        "//! Generated by `scripts/gen_tk_stubs.py`. Do not edit by hand.",
        "//!",
        "//! Slot order is the ABI. These arrays are derived from the Tcl 9.0.4 stub",
        "//! declaration headers as the C preprocessor sees them on macOS"
        " (`MAC_OSX_TCL`,",
        "//! `USE_TCL_STUBS`), because the two platform tables select their members with",
        "//! `#ifdef` arms inside the struct body and a plain text scrape would read the",
        "//! wrong platform's slots.",
        "//!",
        "//! Every slot gets its own function so a call landing on an unimplemented slot",
        "//! identifies itself by index rather than by a shared breakpoint. The traps take",
        "//! no arguments and return nothing: a callee that ignores its arguments is well",
        "//! formed under both SysV x86-64 and AAPCS64, variadic slots included, because",
        "//! the caller owns argument setup and teardown under both.",
        "",
        "use crate::tk::trace::{unimplemented, Table};",
        "use crate::tk::RawStub;",
        "",
    ]

    for struct, prefix, variant in TABLES:
        names = slot_names(text, struct)
        n = len(names)
        reserved = sum(1 for s in names if s.startswith("reserved"))
        out.append(f"// ---- {struct}: {n} slots, {reserved} reserved ----")
        out.append("")
        out.append(f"/// Slot names of `{struct}`, in declaration order.")
        out.append(f"pub static {prefix}_NAMES: [&str; {n}] = [")
        out += [f'    "{name}",' for name in names]
        out.append("];")
        out.append("")
        low = prefix.lower()
        out += [
            f'unsafe extern "C" fn {low}_trap_{i}() {{ unimplemented(Table::{variant}, {i}) }}'
            for i in range(n)
        ]
        out.append("")
        out.append(f"/// One trap per `{struct}` slot, indexed by slot number.")
        out.append(f"pub static {prefix}_TRAPS: [RawStub; {n}] = [")
        out += [f"    {low}_trap_{i}," for i in range(n)]
        out.append("];")
        out.append("")

    dest = Path(__file__).resolve().parent.parent / "src" / "tk" / "generated.rs"
    dest.write_text("\n".join(out) + "\n")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
