#!/usr/bin/env python3
"""Vendor Tcl's clock message catalogues into src/clock_msgs/ and write the manifest.

`clock format -locale de` answers with German month names, a German date order
and a German Gregorian changeover, and every one of those values is data rather
than logic: a catalogue that is one entry out is a wrong answer no reviewer will
catch. So none of them is typed here. Every catalogue comes verbatim out of the
`library/msgs/*.msg` files of the Tcl source release that
`conformance/fetch-suite.sh` fetches and verifies against a pinned SHA-256, and
the reader in `src/clock_locale.rs` is a port of the `::msgcat::mcset` calls
those files consist of.

What this script does:

  * copies each `.msg` file into `src/clock_msgs/`, byte for byte, so `diff -r`
    against a fresh tarball is the whole provenance check;
  * writes `src/clock_msgs.rs`: one `include_str!` per file, in a table sorted
    by the lower-cased locale name the file sets, which is the name
    `msgcat::mcutil::getpreferences` produces and so the name the lookup uses.

The root catalogue is not here. It is not a file: `library/clock.tcl` sets it
with an `::msgcat::mcmset {}` literal, and the port of that literal lives beside
the reader in `src/clock_locale.rs` with a line reference to the source.

Usage, from the crate root:

    sh conformance/fetch-suite.sh
    python3 scripts/gen_clock_msgs.py

Both outputs are committed. Re-run it only to move to a different Tcl release,
and commit the regenerated tree in one change so the manifest and the files it
names never disagree.
"""

import pathlib
import re
import sys

# Where the verified source release lands, relative to the crate root.
VENDOR = "conformance/vendor/tcl9.0.4"

# Every line of every catalogue file is one of these; a file that has anything
# else in it is a file this vendoring step has not been told how to read, and
# the script stops rather than shipping a catalogue the Rust reader will only
# half understand.
SHAPES = (
    re.compile(r"^\s*#"),
    re.compile(r"^\s*$"),
    re.compile(r"^namespace eval ::tcl::clock \{$"),
    re.compile(r"^\}$"),
    re.compile(r"^\s*::msgcat::mcset\s+(?P<locale>[A-Za-z_]+)\s+[A-Z_0-9]+\s"),
    re.compile(r'^\s*"[^"]*"\\?\]?$'),
)


def locale_of(path: pathlib.Path) -> str:
    """The locale name the file's `mcset` calls name, lower-cased.

    msgcat lower-cases a locale on the way in, so `en_GB.msg` and a lookup of
    `en_gb` have to meet at the same key. The name is taken from the file's own
    calls rather than from its stem so that a mismatch is an error here instead
    of a catalogue that can never be reached.
    """
    names = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        matched = None
        for shape in SHAPES:
            matched = shape.match(line)
            if matched:
                break
        if not matched:
            raise SystemExit(f"{path.name}: cannot read line: {line!r}")
        if matched.groupdict().get("locale"):
            names.add(matched.group("locale").lower())
    if len(names) != 1:
        raise SystemExit(f"{path.name}: sets {len(names)} locales, expected 1")
    return names.pop()


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    src_dir = root / VENDOR / "library" / "msgs"
    if not src_dir.is_dir():
        print(
            f"no message catalogue directory at {src_dir}\n"
            "run `sh conformance/fetch-suite.sh` first",
            file=sys.stderr,
        )
        return 1

    out_dir = root / "src" / "clock_msgs"
    out_dir.mkdir(exist_ok=True)

    # The catalogues are redistributed, so the release's own license travels
    # with them rather than being described from memory somewhere else.
    (out_dir / "license.terms").write_bytes(
        (root / VENDOR / "license.terms").read_bytes()
    )

    kept: list[tuple[str, str]] = []
    for path in sorted(src_dir.glob("*.msg")):
        (out_dir / path.name).write_bytes(path.read_bytes())
        kept.append((locale_of(path), path.name))
    kept.sort()

    # Anything vendored by an earlier run and no longer produced would
    # otherwise linger and be included in the crate while nothing reads it.
    for stale in out_dir.glob("*.msg"):
        if stale.name not in {name for _, name in kept}:
            stale.unlink()

    manifest = root / "src" / "clock_msgs.rs"
    release = VENDOR.rsplit("tcl", 1)[1]
    lines = [
        "//! The `clock` message catalogues, as the `.msg` files they came from.",
        "//!",
        "//! Generated by `scripts/gen_clock_msgs.py` from the",
        f"//! `library/msgs/` directory of the Tcl {release}",
        "//! source release — the same checksum-verified tarball",
        "//! `conformance/fetch-suite.sh` unpacks. Do not edit either this file",
        "//! or `src/clock_msgs/`: re-run the generator.",
        "//!",
        "//! The files are byte-for-byte copies, so `diff -r src/clock_msgs",
        "//! conformance/vendor/tcl*/library/msgs` is the whole provenance",
        "//! check. They are read by the port of `::msgcat::mcset` in",
        "//! [`crate::clock_locale`], not by this module, which is data only.",
        "//!",
        "//! The root catalogue is not here: it is an `::msgcat::mcmset {}`",
        "//! literal in `library/clock.tcl` rather than a file, and the port of",
        "//! it sits beside the reader.",
        "//!",
        "//! Tcl is distributed under the license in the release's",
        "//! `license.terms` (a BSD-style permissive license); these",
        "//! catalogues are redistributed under it.",
        "",
        "/// Every locale catalogue, as `(the lower-cased locale name it sets,",
        "/// the text of its `.msg` file)`, sorted by name so a binary search",
        "/// finds one.",
        f"pub const CATALOGUES: [(&str, &str); {len(kept)}] = [",
    ]
    for locale, name in kept:
        lines.append(f'    ("{locale}", include_str!("clock_msgs/{name}")),')
    lines.append("];")
    lines.append("")
    manifest.write_text("\n".join(lines))

    print(f"vendored {len(kept)} clock catalogues into {out_dir}")
    print(f"wrote {manifest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
