#!/usr/bin/env python3
"""Vendor Tcl's encoding tables into src/encodings/ and write the manifest.

`encoding convertfrom` and `encoding convertto` are table lookups, and the
tables are the specification: a mapping that is one code point out is a wrong
answer no reviewer will catch. So none of them is typed here. Every table comes
verbatim out of the `library/encoding/*.enc` files of the Tcl source release
that `conformance/fetch-suite.sh` fetches and verifies against a pinned
SHA-256, and the loader in `src/cmd_encoding.rs` is a port of the reader those
files were written for (`LoadTableEncoding`, generic/tclEncoding.c:1954).

What this script does:

  * copies each table-type `.enc` file into `src/encodings/`, byte for byte, so
    `diff -r` against a fresh tarball is the whole provenance check;
  * writes `src/encoding_tables.rs`: one `include_str!` per file, in a table
    sorted by name.

The three escape-type files (`iso2022`, `iso2022-jp`, `iso2022-kr`) are left
out. They are not tables but state machines with a second file format
(`LoadEscapeEncoding`), `src/cmd_encoding.rs` refuses them by name, and
vendoring data nothing reads would be a lie about what is supported.

Usage, from the crate root:

    sh conformance/fetch-suite.sh
    python3 scripts/gen_encoding_tables.py

Both outputs are committed. Re-run it only to move to a different Tcl release,
and commit the regenerated tree in one change so the manifest and the files it
names never disagree.
"""

import pathlib
import sys

# Where the verified source release lands, relative to the crate root.
VENDOR = "conformance/vendor/tcl9.0.4"
# Only these two types are tables the Rust loader can read; 'E' is the escape
# state machine and is refused by name instead.
TABLE_TYPES = ("S", "D", "M")


def enc_type(path: pathlib.Path) -> str:
    """The type letter on the second line of a `.enc` file."""
    with path.open("rb") as f:
        f.readline()
        return f.readline().strip().decode("ascii")


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    src_dir = root / VENDOR / "library" / "encoding"
    if not src_dir.is_dir():
        print(
            f"no encoding directory at {src_dir}\n"
            "run `sh conformance/fetch-suite.sh` first",
            file=sys.stderr,
        )
        return 1

    out_dir = root / "src" / "encodings"
    out_dir.mkdir(exist_ok=True)

    # The tables are redistributed, so the release's own license travels with
    # them rather than being described from memory somewhere else.
    (out_dir / "license.terms").write_bytes(
        (root / VENDOR / "license.terms").read_bytes()
    )

    kept: list[tuple[str, str]] = []
    skipped: list[str] = []
    for path in sorted(src_dir.glob("*.enc")):
        kind = enc_type(path)
        if kind not in TABLE_TYPES:
            skipped.append(f"{path.stem} ({kind})")
            continue
        (out_dir / path.name).write_bytes(path.read_bytes())
        kept.append((path.stem, path.name))

    # Anything that was vendored by an earlier run and is no longer produced
    # would otherwise linger and be included in the crate while nothing reads
    # it.
    for stale in out_dir.glob("*.enc"):
        if stale.name not in {name for _, name in kept}:
            stale.unlink()

    manifest = root / "src" / "encoding_tables.rs"
    lines = [
        "//! The encoding tables, as the `.enc` files they came from.",
        "//!",
        "//! Generated by `scripts/gen_encoding_tables.py` from the",
        f"//! `library/encoding/` directory of the Tcl {VENDOR.rsplit('tcl', 1)[1]}",
        "//! source release — the same checksum-verified tarball",
        "//! `conformance/fetch-suite.sh` unpacks. Do not edit either this file",
        "//! or `src/encodings/`: re-run the generator.",
        "//!",
        "//! The files are byte-for-byte copies, so `diff -r src/encodings",
        "//! conformance/vendor/tcl*/library/encoding` is the whole provenance",
        "//! check. They are read by the port of `LoadTableEncoding` in",
        "//! [`crate::cmd_encoding`], not by this module, which is data only.",
        "//!",
        "//! Tcl is distributed under the license in the release's",
        "//! `license.terms` (a BSD-style permissive license); these tables are",
        "//! redistributed under it.",
        "",
        "/// Every table encoding, as `(name, the text of its `.enc` file)`,",
        "/// sorted by name so a binary search finds one and `encoding names`",
        "/// has a fixed order.",
        f"pub const TABLES: [(&str, &str); {len(kept)}] = [",
    ]
    for stem, name in kept:
        lines.append(f'    ("{stem}", include_str!("encodings/{name}")),')
    lines.append("];")
    lines.append("")
    manifest.write_text("\n".join(lines))

    print(f"vendored {len(kept)} table encodings into {out_dir}")
    print(f"wrote {manifest}")
    if skipped:
        print("left out (not a table): " + ", ".join(skipped))
    return 0


if __name__ == "__main__":
    sys.exit(main())
