//! The encoding tables, as the `.enc` files they came from.
//!
//! Generated by `scripts/gen_encoding_tables.py` from the
//! `library/encoding/` directory of the Tcl 9.0.4
//! source release — the same checksum-verified tarball
//! `conformance/fetch-suite.sh` unpacks. Do not edit either this file
//! or `src/encodings/`: re-run the generator.
//!
//! The files are byte-for-byte copies, so `diff -r src/encodings
//! conformance/vendor/tcl*/library/encoding` is the whole provenance
//! check. They are read by the port of `LoadTableEncoding` in
//! [`crate::cmd_encoding`], not by this module, which is data only.
//!
//! Tcl is distributed under the license in the release's
//! `license.terms` (a BSD-style permissive license); these tables are
//! redistributed under it.

/// Every table encoding, as `(name, the text of its `.enc` file)`,
/// sorted by name so a binary search finds one and `encoding names`
/// has a fixed order.
pub const TABLES: [(&str, &str); 80] = [
    ("ascii", include_str!("encodings/ascii.enc")),
    ("big5", include_str!("encodings/big5.enc")),
    ("cns11643", include_str!("encodings/cns11643.enc")),
    ("cp1250", include_str!("encodings/cp1250.enc")),
    ("cp1251", include_str!("encodings/cp1251.enc")),
    ("cp1252", include_str!("encodings/cp1252.enc")),
    ("cp1253", include_str!("encodings/cp1253.enc")),
    ("cp1254", include_str!("encodings/cp1254.enc")),
    ("cp1255", include_str!("encodings/cp1255.enc")),
    ("cp1256", include_str!("encodings/cp1256.enc")),
    ("cp1257", include_str!("encodings/cp1257.enc")),
    ("cp1258", include_str!("encodings/cp1258.enc")),
    ("cp165", include_str!("encodings/cp165.enc")),
    ("cp437", include_str!("encodings/cp437.enc")),
    ("cp737", include_str!("encodings/cp737.enc")),
    ("cp775", include_str!("encodings/cp775.enc")),
    ("cp850", include_str!("encodings/cp850.enc")),
    ("cp852", include_str!("encodings/cp852.enc")),
    ("cp855", include_str!("encodings/cp855.enc")),
    ("cp857", include_str!("encodings/cp857.enc")),
    ("cp860", include_str!("encodings/cp860.enc")),
    ("cp861", include_str!("encodings/cp861.enc")),
    ("cp862", include_str!("encodings/cp862.enc")),
    ("cp863", include_str!("encodings/cp863.enc")),
    ("cp864", include_str!("encodings/cp864.enc")),
    ("cp865", include_str!("encodings/cp865.enc")),
    ("cp866", include_str!("encodings/cp866.enc")),
    ("cp869", include_str!("encodings/cp869.enc")),
    ("cp874", include_str!("encodings/cp874.enc")),
    ("cp932", include_str!("encodings/cp932.enc")),
    ("cp936", include_str!("encodings/cp936.enc")),
    ("cp949", include_str!("encodings/cp949.enc")),
    ("cp950", include_str!("encodings/cp950.enc")),
    ("dingbats", include_str!("encodings/dingbats.enc")),
    ("ebcdic", include_str!("encodings/ebcdic.enc")),
    ("euc-cn", include_str!("encodings/euc-cn.enc")),
    ("euc-jp", include_str!("encodings/euc-jp.enc")),
    ("euc-kr", include_str!("encodings/euc-kr.enc")),
    ("gb12345", include_str!("encodings/gb12345.enc")),
    ("gb1988", include_str!("encodings/gb1988.enc")),
    ("gb2312-raw", include_str!("encodings/gb2312-raw.enc")),
    ("gb2312", include_str!("encodings/gb2312.enc")),
    ("iso8859-1", include_str!("encodings/iso8859-1.enc")),
    ("iso8859-10", include_str!("encodings/iso8859-10.enc")),
    ("iso8859-11", include_str!("encodings/iso8859-11.enc")),
    ("iso8859-13", include_str!("encodings/iso8859-13.enc")),
    ("iso8859-14", include_str!("encodings/iso8859-14.enc")),
    ("iso8859-15", include_str!("encodings/iso8859-15.enc")),
    ("iso8859-16", include_str!("encodings/iso8859-16.enc")),
    ("iso8859-2", include_str!("encodings/iso8859-2.enc")),
    ("iso8859-3", include_str!("encodings/iso8859-3.enc")),
    ("iso8859-4", include_str!("encodings/iso8859-4.enc")),
    ("iso8859-5", include_str!("encodings/iso8859-5.enc")),
    ("iso8859-6", include_str!("encodings/iso8859-6.enc")),
    ("iso8859-7", include_str!("encodings/iso8859-7.enc")),
    ("iso8859-8", include_str!("encodings/iso8859-8.enc")),
    ("iso8859-9", include_str!("encodings/iso8859-9.enc")),
    ("jis0201", include_str!("encodings/jis0201.enc")),
    ("jis0208", include_str!("encodings/jis0208.enc")),
    ("jis0212", include_str!("encodings/jis0212.enc")),
    ("koi8-r", include_str!("encodings/koi8-r.enc")),
    ("koi8-ru", include_str!("encodings/koi8-ru.enc")),
    ("koi8-t", include_str!("encodings/koi8-t.enc")),
    ("koi8-u", include_str!("encodings/koi8-u.enc")),
    ("ksc5601", include_str!("encodings/ksc5601.enc")),
    ("macCentEuro", include_str!("encodings/macCentEuro.enc")),
    ("macCroatian", include_str!("encodings/macCroatian.enc")),
    ("macCyrillic", include_str!("encodings/macCyrillic.enc")),
    ("macDingbats", include_str!("encodings/macDingbats.enc")),
    ("macGreek", include_str!("encodings/macGreek.enc")),
    ("macIceland", include_str!("encodings/macIceland.enc")),
    ("macJapan", include_str!("encodings/macJapan.enc")),
    ("macRoman", include_str!("encodings/macRoman.enc")),
    ("macRomania", include_str!("encodings/macRomania.enc")),
    ("macThai", include_str!("encodings/macThai.enc")),
    ("macTurkish", include_str!("encodings/macTurkish.enc")),
    ("macUkraine", include_str!("encodings/macUkraine.enc")),
    ("shiftjis", include_str!("encodings/shiftjis.enc")),
    ("symbol", include_str!("encodings/symbol.enc")),
    ("tis-620", include_str!("encodings/tis-620.enc")),
];
